// export { default as Button } from "./components/Button/index";
import "./styles/index.scss";
export { default as Box } from "./components/Box/index";
// new components
export { default as ZoomPhoto } from "./components/ZoomPhoto/index";
export { default as PageHeader } from "./components/PageHeader/index";
export { default as Switch } from "./components/Switch/index";
export { default as Tag } from "./components/Tag/index";
export { default as Collapse } from "./components/Collapse/index";
export { default as ConfigProvider } from "./components/ConfigProvider/index";
export { default as Popover } from "./components/Popover/index";
export { default as Tabs } from "./components/Tabs/index";
export { default as Empty } from "./components/Empty/index";
export { default as Drawer } from "./components/Drawer/index";
export { default as Col } from "./components/Col/index";
export { default as Row } from "./components/Row/index";
export { default as Badge } from "./components/Badge/index";
export { default as Table } from "./components/Table/index";
export { default as Popconfirm } from "./components/Popconfirm/index";
export { default as message } from "./components/message/index";
export { default as Tooltip } from "./components/Tooltip/index";
export { default as Progress } from "./components/Progress/index";
export { default as Spin } from "./components/Spin/index";
export { default as Modal } from "./components/Modal/index";
export { default as Upload } from "./components/Upload/index";
export { default as Transfer } from "./components/Transfer/index";
export { default as Slider } from "./components/Slider/index";
export { default as Select } from "./components/Select/index";
export { default as Radio } from "./components/Radio/index";
export { default as InputNumber } from "./components/InputNumber/index";
export { default as Input } from "./components/Input/index";
export { default as Form } from "./components/Form/index";
export { default as DatePicker } from "./components/DatePicker/index";
export { default as Checkbox } from "./components/Checkbox/index";
export { default as AutoComplete } from "./components/AutoComplete/index";
export { default as Pagination } from "./components/Pagination/index";
export { default as Menu } from "./components/Menu/index";
export { default as Dropdown } from "./components/Dropdown/index";
export { default as Space } from "./components/Space/index";
export { default as Divider } from "./components/Divider/index";
export { default as IconTooltip } from "./components/IconTooltip/index";
export { default as Button } from "./components/Button/index";
export { default as WhiteTopBar } from "./components/WhiteTopBar/index";
// export { default as Icon } from "./components/Icon/index";
